<?php
/**
 * @category   Jcc
 * @package    Jcc_Mform
 * @author     jcc@jccbweb.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Jcc\Mform\Model\ResourceModel;

class Mform extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    /**
     * Define main table
     */
    protected function _construct()
    {
        $this->_init('jcc_mform', 'mform_id');   //here "jcc_mform" is table name and "mform_id" is the primary key of custom table
    }
}