<?php
/**
 * @category   Jcc
 * @package    Jcc_Mform
 * @author     jcc@jccbweb.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Jcc\Mform\Block\Adminhtml\Items\Edit\Tab;

use Magento\Backend\Block\Widget\Form\Generic;
use Magento\Backend\Block\Widget\Tab\TabInterface;

class Main extends Generic implements TabInterface
{
    protected $_wysiwygConfig;
 
    public function __construct(
        \Magento\Backend\Block\Template\Context $context, 
        \Magento\Framework\Registry $registry, 
        \Magento\Framework\Data\FormFactory $formFactory,  
        \Magento\Cms\Model\Wysiwyg\Config $wysiwygConfig, 
        array $data = []
    ) 
    {
        $this->_wysiwygConfig = $wysiwygConfig;
        parent::__construct($context, $registry, $formFactory, $data);
    }

    /**
     * {@inheritdoc}
     */
    public function getTabLabel()
    {
        return __('Item Information');
    }

    /**
     * {@inheritdoc}
     */
    public function getTabTitle()
    {
        return __('Item Information');
    }

    /**
     * {@inheritdoc}
     */
    public function canShowTab()
    {
        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function isHidden()
    {
        return false;
    }

    /**
     * Prepare form before rendering HTML
     *
     * @return $this
     * @SuppressWarnings(PHPMD.NPathComplexity)
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    protected function _prepareForm()
    {
        $model = $this->_coreRegistry->registry('current_jcc_mform_items');
        /** @var \Magento\Framework\Data\Form $form */
        $form = $this->_formFactory->create();
        $form->setHtmlIdPrefix('item_');
        $fieldset = $form->addFieldset('base_fieldset', ['legend' => __('Item Information')]);
        if ($model->getId()) {
            $fieldset->addField('mform_id', 'hidden', ['name' => 'mform_id']);
        }
        $fieldset->addField(
            'Btype',
            'text',
            ['name' => 'Btype', 'label' => __('Business Type'), 'title' => __('Business Type'), 'required' => true]
        );

        $fieldset->addField(
            'Firstname',
            'text',
            ['name' => 'Firstname', 'label' => __('F. Name'), 'title' => __('F. Name'), 'required' => true]
        );
        $fieldset->addField(
            'Middle',
            'text',
            ['name' => 'Middle', 'label' => __('Middle'), 'title' => __('Middle'), 'required' => true]
        );
        $fieldset->addField(
            'Lastname',
            'text',
            ['name' => 'Lastname', 'label' => __('Last Name'), 'title' => __('Last Name'), 'required' => true]
        );

        $fieldset->addField(
            'address',
            'text',
            ['name' => 'address', 'label' => __('address'), 'title' => __('address'), 'required' => true]
        );

        $fieldset->addField(
            'city',
            'text',
            ['name' => 'city', 'label' => __('City'), 'title' => __('City'), 'required' => true]
        );
        $fieldset->addField(
            'state',
            'text',
            ['name' => 'state', 'label' => __('State'), 'title' => __('State'), 'required' => true]
        );
        $fieldset->addField(
            'zip',
            'text',
            ['name' => 'zip', 'label' => __('Zip'), 'title' => __('Zip'), 'required' => true]
        );
        $fieldset->addField(
            'contactCounty',
            'text',
            ['name' => 'contactCounty', 'label' => __('County'), 'title' => __('County'), 'required' => true]
        );
        $fieldset->addField(
            'contactMailingaddress',
            'text',
            ['name' => 'contactMailingaddress', 'label' => __('M address'), 'title' => __('M address'), 'required' => true]
        );
        $fieldset->addField(
            'contactPhone',
            'text',
            ['name' => 'contactPhone', 'label' => __('M Phone'), 'title' => __('M Phone'), 'required' => true]
        );
        $fieldset->addField(
            'contactPhoneb',
            'text',
            ['name' => 'contactPhoneb', 'label' => __('M Phone B'), 'title' => __('M Phone B'), 'required' => true]
        );
        $fieldset->addField(
            'option1',
            'text',
            ['name' => 'option1', 'label' => __('option1'), 'title' => __('option1'), 'required' => true]
        );
        $fieldset->addField(
            'option2',
            'text',
            ['name' => 'option2', 'label' => __('option2'), 'title' => __('option2'), 'required' => true]
        );
        $fieldset->addField(
            'option3',
            'text',
            ['name' => 'option3', 'label' => __('option3'), 'title' => __('option3'), 'required' => true]
        );

        $fieldset->addField(
            'option3',
            'text',
            ['name' => 'option3', 'label' => __('option3'), 'title' => __('option3'), 'required' => true]
        );
        $fieldset->addField(
            'company1choice',
            'text',
            ['name' => 'company1choice', 'label' => __('Company choice '), 'title' => __('Company choice'), 'required' => true]
        );

        $fieldset->addField(
            'company2choice',
            'text',
            ['name' => 'company2choice', 'label' => __('Company choice '), 'title' => __('Company choice'), 'required' => true]
        );
        $fieldset->addField(
            'company3choice',
            'text',
            ['name' => 'company3choice', 'label' => __('Company choice '), 'title' => __('Company choice'), 'required' => true]
        );
        $fieldset->addField(
            'option1ending',
            'text',
            ['name' => 'option1ending', 'label' => __('Ending'), 'title' => __('Ending'), 'required' => true]
        );
        $fieldset->addField(
            'option2ending',
            'text',
            ['name' => 'option2ending', 'label' => __('Ending'), 'title' => __('Ending'), 'required' => true]
        );
        $fieldset->addField(
            'option3ending',
            'text',
            ['name' => 'option3ending', 'label' => __('Ending'), 'title' => __('Ending'), 'required' => true]
        );
        $fieldset->addField(
            'option4ending',
            'text',
            ['name' => 'option4ending', 'label' => __('Ending'), 'title' => __('Ending'), 'required' => true]
        );
        $fieldset->addField(
            'option5ending',
            'text',
            ['name' => 'option5ending', 'label' => __('Ending'), 'title' => __('Ending'), 'required' => true]
        );
        $fieldset->addField(
            'option6ending',
            'text',
            ['name' => 'option6ending', 'label' => __('Ending'), 'title' => __('Ending'), 'required' => true]
        );

        $fieldset->addField(
            'activityBusiness',
            'text',
            ['name' => 'activityBusiness', 'label' => __('Activity'), 'title' => __('Activity'), 'required' => true]
        );
        $fieldset->addField(
            'addressBusiness',
            'text',
            ['name' => 'addressBusiness', 'label' => __('Address B'), 'title' => __('Address B'), 'required' => true]
        );
        $fieldset->addField(
            'businessCity',
            'text',
            ['name' => 'businessCity', 'label' => __('B City'), 'title' => __('B City'), 'required' => true]
        );
        $fieldset->addField(
            'businessState',
            'text',
            ['name' => 'businessState', 'label' => __('B State'), 'title' => __('B State'), 'required' => true]
        );
        $fieldset->addField(
            'businessZip',
            'text',
            ['name' => 'businessZip', 'label' => __('B Zip'), 'title' => __('B Zip'), 'required' => true]
        );

        $fieldset->addField(
            'mailingBusiness',
            'text',
            ['name' => 'mailingBusiness', 'label' => __('Mailing B'), 'title' => __('Mailing B'), 'required' => true]
        );
        $fieldset->addField(
            'mailingBusinessCity',
            'text',
            ['name' => 'mailingBusinessCity', 'label' => __('Mailing City'), 'title' => __('Mailing City'), 'required' => true]
        );
        $fieldset->addField(
            'mailingBusinessState',
            'text',
            ['name' => 'mailingBusinessState', 'label' => __('Mailing State'), 'title' => __('Mailing State'), 'required' => true]
        );
        $fieldset->addField(
            'mailingBusinessZip',
            'text',
            ['name' => 'mailingBusinessZip', 'label' => __('Mailing Zip'), 'title' => __('Mailing Zip'), 'required' => true]
        );
        $fieldset->addField(
            'latestdate',
            'text',
            ['name' => 'latestdate', 'label' => __('Date'), 'title' => __('Date'), 'required' => true]
        );
        $fieldset->addField(
            'perpetual',
            'text',
            ['name' => 'perpetual', 'label' => __('Perpetual'), 'title' => __('Perpetual'), 'required' => true]
        );
        $fieldset->addField(
            'agentFirstname',
            'text',
            ['name' => 'agentFirstname', 'label' => __('A Firstname'), 'title' => __('A Firstname'), 'required' => true]
        );
        $fieldset->addField(
            'agentMiddle',
            'text',
            ['name' => 'agentMiddle', 'label' => __('A Middle'), 'title' => __('A Middle'), 'required' => true]
        );

        $fieldset->addField(
            'agentLastname',
            'text',
            ['name' => 'agentLastname', 'label' => __('A Last Name'), 'title' => __('A Last Name'), 'required' => true]
        );
        $fieldset->addField(
            'agentStreet',
            'text',
            ['name' => 'agentLStreet', 'label' => __('A Street'), 'title' => __('A Street'), 'required' => true]
        );
        $fieldset->addField(
            'agentCity',
            'text',
            ['name' => 'agentCity', 'label' => __('A City'), 'title' => __('A City'), 'required' => true]
        );
        $fieldset->addField(
            'agentState',
            'text',
            ['name' => 'agentState', 'label' => __('A State'), 'title' => __('A State'), 'required' => true]
        );
        $fieldset->addField(
            'agentZip',
            'text',
            ['name' => 'agentZip', 'label' => __('A Zip'), 'title' => __('A Zip'), 'required' => true]
        );
        $fieldset->addField(
            'agentZip',
            'text',
            ['name' => 'agentZip', 'label' => __('A Zip'), 'title' => __('A Zip'), 'required' => true]
        );
        $fieldset->addField(
            'agentPhone',
            'text',
            ['name' => 'agentPhone', 'label' => __('A Phone'), 'title' => __('A Phone'), 'required' => true]
        );
        $fieldset->addField(
            'agentPhoneb',
            'text',
            ['name' => 'agentPhoneb', 'label' => __('A Phone B'), 'title' => __('A Phone B'), 'required' => true]
        );
        $fieldset->addField(
            'moption1',
            'text',
            ['name' => 'moption1', 'label' => __('Option1'), 'title' => __('Option1'), 'required' => true]
        );
        $fieldset->addField(
            'moption2',
            'text',
            ['name' => 'moption2', 'label' => __('Option2'), 'title' => __('Option2'), 'required' => true]
        );
        $fieldset->addField(
            'moption3',
            'text',
            ['name' => 'moption3', 'label' => __('Option3'), 'title' => __('Option3'), 'required' => true]
        );
        $fieldset->addField(
            'moption4',
            'text',
            ['name' => 'moption4', 'label' => __('Option4'), 'title' => __('Option4'), 'required' => true]
        );

        $fieldset->addField(
            'author',
            'text',
            ['name' => 'author', 'label' => __('Author'), 'title' => __('Author'), 'required' => true]
        );

        $fieldset->addField(
            'status',
            'select',
            ['name' => 'status', 'label' => __('Status'), 'title' => __('Status'),  'options'   => [0 => 'Disable', 1 => 'Enable'], 'required' => true]
        );
        $fieldset->addField(
            'content',
            'editor',
            [
                'name' => 'content',
                'label' => __('Content'),
                'title' => __('Content'),
                'style' => 'height:26em;',
                'required' => true,
                'config'    => $this->_wysiwygConfig->getConfig(),
                'wysiwyg' => true
            ]
        );
        
        $form->setValues($model->getData());
        $this->setForm($form);
        return parent::_prepareForm();
    }
}
