<!--<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">  -->
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div style="height:10px;"></div>
<div class="assessment-container container">
    <div class="row">
        <div class="col-md-12 form-box">
            <form class="registration-form" action="<?php echo $block->getBaseUrl().'dbainfo/index/save'; ?>">

                <fieldset style="display: block; border: 1px solid #dedede;">



                    <div class="form-top">
                        <div class="form-top-left">
                            <h3> DBA INFORMATION .</h3>
                            <p>Client Information </p>
                        </div>
                    </div>


                    <div class="form-bottom">




                        <div class="row">
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <div class="wrap-field">

                                        <input type="text"  name="dbaFirstname" id="dbaFirstname"  placeholder="First Name" class="required form-control">
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <div class="wrap-field">

                                        <input type="text"  name="dbaMiddle"  placeholder="Middle"    placeholder="Middle" class="form-control">
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <div class="wrap-field">

                                        <input type="text"  name="dbaLastname"  id="dbaLastname"  placeholder="Last Name" class="form-control">
                                    </div>
                                </div>
                            </div>
                        </div><!--/ end of the row-->



                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="wrap-field">

                                        <input type="text"name="dbaAddress"  placeholder="Address"   class="form-control">
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="wrap-field">

                                        <input type="text"  name="dbaCity"     placeholder="City" class="form-control">
                                    </div>
                                </div>
                            </div>
                        </div><!--// end row -->


                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="wrap-field">

                                        <input type="text" name="dbaState"  id="dbaState"  placeholder="State" class="required form-control">
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="wrap-field">

                                        <input type="text"  name="dbaZip"  placeholder="Zip" class="form-control">
                                    </div>
                                </div>
                            </div>
                        </div><!--// end row -->



                        <div class="row">
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <div class="wrap-field">

                                        <input type="text"  name="dbaPhone"  placeholder="Phone" class="form-control">
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <div class="wrap-field">

                                        <input type="text" name="dbaCell"  placeholder="Cell Phone" class="form-control">
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <div class="wrap-field">

                                        <input type="text" name="dbaEmail"  placeholder="Email" class="form-control">
                                    </div>
                                </div>
                            </div>
                        </div><!--// end row -->




                        <div class="row">
                            <div class="col-sm-12">
                                <div class="customer-info">
                                    The contact address is the primary address used for the delivery of any documents or products related to your order.
                                    This address is used for internal purposes only and will not be shared with any third parties or other outside agencies unless provided in any subsequent pages of the order process which require the intake of an address.
                                </div>
                            </div>
                        </div>


                        <button type="button" class="btn btn-next">Next</button>
                    </div>
                </fieldset>







                <fieldset  style="border: 1px solid #dedede;">
                    <div class="form-top">
                        <div class="form-top-left">
                            <h3>OWNER(S) INFORMATION </h3>
                            <p>Information
                            </p>
                        </div>
                    </div>

                    <!-- Here is the form -->



                    <div class="row">

                        <div class="col-sm-4">
                            <div class="form-group">
                                <div class="wrap-field">

                                    <input type="text"  name="dbaOFirstname"  placeholder="First Name" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <div class="wrap-field">

                                    <input type="text"  name="dbaOMiddle"  placeholder="Middle" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <div class="wrap-field">

                                    <input type="text"  name="dbaOLastname"  placeholder="Last Name" class="form-control">
                                </div>
                            </div>
                        </div>
                    </div><!--/ end of the row -->


                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <div class="wrap-field">

                                    <input type="text" name="dbaOAddress"  placeholder="Address" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <div class="wrap-field">

                                </div>
                            </div>
                        </div>
                    </div><!--// end row -->


                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <div class="wrap-field">

                                    <input type="text"  name="dbaOCity"  placeholder="City" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <div class="wrap-field">

                                    <input type="text" name="dbaOState"  placeholder="State" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <div class="wrap-field">

                                    <input type="text" name="dbaOZip"  placeholder="Zip Code" class="form-control">
                                </div>
                            </div>
                        </div>
                    </div><!--// end row -->



                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <div class="wrap-field">

                                    <input type="text"  name="dbaOPhone"  placeholder="Phone" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <div class="wrap-field">

                                    <input type="text" name="dbaOCell"  placeholder="Cell Phone" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <div class="wrap-field">

                                    <input type="text" name="dbaOEmail"  placeholder="Email" class="form-control">
                                </div>
                            </div>
                        </div>
                    </div><!--// end row -->



                    <div class="form-top-left">
                        <h3>OWNER(S) INFORMATION</h3>
                    </div>


                    <div class="row">

                        <div class="col-sm-4">
                            <div class="form-group">
                                <div class="wrap-field">

                                    <input type="text"  name="dbaOFirstname2"  placeholder="First Name" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <div class="wrap-field">

                                    <input type="text"  name="dbaOMiddle2"  placeholder="Middle" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <div class="wrap-field">

                                    <input type="text"  name="dbaOLastname2"  placeholder="Last Name" class="form-control">
                                </div>
                            </div>
                        </div>
                    </div><!--/ end of the row -->


                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <div class="wrap-field">

                                    <input type="text" name="dbaOAddress2"  placeholder="Address" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <div class="wrap-field">

                                </div>
                            </div>
                        </div>
                    </div><!--// end row -->


                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <div class="wrap-field">

                                    <input type="text"  name="dbaOCity2"  placeholder="City" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <div class="wrap-field">

                                    <input type="text" name="dbaOState2"  placeholder="State" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <div class="wrap-field">

                                    <input type="text" name="dbaOZip2"  placeholder="Zip Code" class="form-control">
                                </div>
                            </div>
                        </div>
                    </div><!--// end row -->



                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <div class="wrap-field">

                                    <input type="text"  name="dbaOPhone2"  placeholder="Phone" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <div class="wrap-field">

                                    <input type="text" name="dbaOCell2"  placeholder="Cell Phone" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <div class="wrap-field">

                                    <input type="text" name="dbaOEmail2"  placeholder="Email" class="form-control">
                                </div>
                            </div>
                        </div>
                    </div><!--// end row -->

                    <div class="form-top-left">
                        <h3>PROPOSED NAME  FOR DBA</h3>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <div class="wrap-field">
                                    <ul style="list-style: none; ">

                                        <li>
                                            <!-- Material unchecked -->
                                            <div class="text-imput">Option 1</div>
                                            <input type="text" name="dbaBusiness1"  placeholder="Business Name" class="form-control">
                                        </li>
                                        <li>
                                            <!-- Material unchecked -->
                                            <div class="text-imput">Option 2</div>
                                            <input type="text" name="dbaBusiness2"  placeholder="Business Name" class="form-control valid only_character js-upper-first required">


                                        </li>
                                        <li>
                                            <!-- Material unchecked -->
                                            <div class="text-imput">Option 3</div>
                                            <input type="text" name="dbaBusiness3"  placeholder="Business Name" class="form-control valid only_character js-upper-first required">


                                        </li>

                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div><!--// end row -->


                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <div class="wrap-field">

                                    <input type="text" name="dbaBAddressB"  placeholder="Address" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <div class="wrap-field">
                                    
                                    <input type="text" name="startDate"  placeholder="Start Date  (00/00/0000)" class="form-control">
                                </div>
                            </div>
                        </div>
                    </div><!--// end row -->
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <div class="wrap-field">

                                    <textarea name="content" class="form-control" placeholder="Message"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="form-bottom">
                        <button type="button" class="btn btn-previous">Previous</button>
                        <button type="submit" class="btn">Submit</button>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>


<script>



    require([
        "jquery"
    ], function($){
        $(document).ready(function () {

            console.log("jcc");

            $('.registration-form fieldset:first-child').fadeIn('slow');

            $('.registration-form input[type="text"].required').on('focus', function () {
                $(this).removeClass('input-error');
            });
            /*
            $('.registration-form input[type="text"]').on('focus', function () {
                $(this).removeClass('input-error');
            });
            */


            // next step
            $('.registration-form .btn-next').on('click', function () {
                var parent_fieldset = $(this).parents('fieldset');
                var next_step = true;

                parent_fieldset.find('input[type="text"].required ,input[type="email"]').each(function () {
                    if ($(this).val() == "") {
                        $(this).addClass('input-error');
                        next_step = false;
                    } else {
                        $(this).removeClass('input-error');
                    }
                });

                if (next_step) {
                    parent_fieldset.fadeOut(400, function () {
                        $(this).next().fadeIn();
                    });
                }

            });

            // previous step
            $('.registration-form .btn-previous').on('click', function () {
                $(this).parents('fieldset').fadeOut(400, function () {
                    $(this).prev().fadeIn();
                });
            });

            // submit
            $('.registration-form').on('submit', function (e) {

                //$(this).find('input[type="text"],input[type="email"]').each(function () {
                $(this).find('input[type="text"].required, input[type="email"]').each(function () {

                    if ($(this).val() == "") {
                        e.preventDefault();
                        $(this).addClass('input-error');
                    } else {
                        $(this).removeClass('input-error');
                    }
                });

            });


        });
    });

</script>
<style>
    input[type="text"],
    input[type="email"],
    input[type="date"],
    select.form-control {
        height: 40px;
        margin: 10px;
        padding: 0 20px;
        vertical-align: middle;
        background: #fff;
        border: 1px solid #ddd;
        font-family: 'Roboto', sans-serif;
        font-size: 16px;
        font-weight: 300;
        line-height: 50px;
        color: #403e3e;
        -moz-border-radius: 4px;
        -webkit-border-radius: 4px;
        border-radius: 4px;
        -moz-box-shadow: none;
        -webkit-box-shadow: none;
        box-shadow: none;
        -o-transition: all .3s;
        -moz-transition: all .3s;
        -webkit-transition: all .3s;
        -ms-transition: all .3s;
        transition: all .3s;
    }

    input[type="file"] {
        height: 35px;
        margin: 0;
        padding: 0 20px;
        vertical-align: bottom;
        background: #f8f8f8;
        border: 3px solid #ddd;
        font-family: 'Roboto', sans-serif;
        font-size: 16px;
        font-weight: 300;
        line-height: 30px;
        color: #888;
        -moz-border-radius: 4px;
        -webkit-border-radius: 4px;
        border-radius: 4px;
        -moz-box-shadow: none;
        -webkit-box-shadow: none;
        box-shadow: none;
        -o-transition: all .3s;
        -moz-transition: all .3s;
        -webkit-transition: all .3s;
        -ms-transition: all .3s;
        transition: all .3s;
    }

    input[type=radio] {
        margin-top: 8px !important;
    }

    textarea,
    textarea.form-control {
        padding-top: 10px;
        padding-bottom: 10px;
        line-height: 30px;
    }

    input[type="text"]:focus,
    input[type="password"]:focus,
    textarea:focus,
    textarea.form-control:focus {
        outline: 0;
        background: #fff;
        border: 3px solid #ccc;
        -moz-box-shadow: none;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    input[type="text"]:-moz-placeholder,
    input[type="password"]:-moz-placeholder,
    textarea:-moz-placeholder,
    textarea.form-control:-moz-placeholder {
        color: #595959;
    }

    input[type="text"]:-ms-input-placeholder,
    input[type="password"]:-ms-input-placeholder,
    textarea:-ms-input-placeholder,
    textarea.form-control:-ms-input-placeholder {
        color: #595959;
    }

    input[type="text"]::-webkit-input-placeholder,
    input[type="password"]::-webkit-input-placeholder,
    textarea::-webkit-input-placeholder,
    textarea.form-control::-webkit-input-placeholder {
        color: #595959;
    }

    button.btn {
        height: 50px;
        margin: 0;
        padding: 0 20px;
        vertical-align: middle;
        background: #00aeef;
        border: 0;
        font-family: 'Roboto', sans-serif;
        font-size: 16px;
        font-weight: 300;
        line-height: 50px;
        color: #fff;
        -moz-border-radius: 4px;
        -webkit-border-radius: 4px;
        border-radius: 4px;
        text-shadow: none;
        -moz-box-shadow: none;
        -webkit-box-shadow: none;
        box-shadow: none;
        -o-transition: all .3s;
        -moz-transition: all .3s;
        -webkit-transition: all .3s;
        -ms-transition: all .3s;
        transition: all .3s;
    }

    button.btn:hover {
        opacity: 0.6;
        color: #fff;
    }

    button.btn:active {
        outline: 0;
        opacity: 0.6;
        color: #fff;
        -moz-box-shadow: none;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    button.btn:focus {
        outline: 0;
        opacity: 0.6;
        background: #00aeef;
    ;
        color: #fff;
    }

    button.btn:active:focus,
    button.btn.active:focus {
        outline: 0;
        opacity: 0.6;
        background: #00aeef;
        color: #fff;
    }


    /*style.css

    body {
        font-family: 'Roboto', sans-serif;
        font-size: 16px;
        font-weight: 300;
        color: #888;
        line-height: 30px;
        text-align: center;
    }
    **/
    strong {
        font-weight: 500;
    }

    a,
    a:hover,
    a:focus {
        color: #00aeef;
    ;
        text-decoration: none;
        -o-transition: all .3s;
        -moz-transition: all .3s;
        -webkit-transition: all .3s;
        -ms-transition: all .3s;
        transition: all .3s;
    }

    h1,
    h2 {
        margin-top: 10px;
        font-size: 38px;
        font-weight: 100;
        color: #555;
        line-height: 50px;
    }

    h3 {
        font-size: 18px;
        font-weight: 300;
        color: #555;
        line-height: 30px;
    }

    ::-moz-selection {
        background: #00aeef;
    ;
        color: #fff;
        text-shadow: none;
    }

    ::selection {
        background: #00aeef;
        color: #fff;
        text-shadow: none;
    }

    .btn-link-1 {
        display: inline-block;
        height: 50px;
        margin: 0 5px;
        padding: 16px 20px 0 20px;
        background: #00aeef;
        font-size: 16px;
        font-weight: 300;
        line-height: 16px;
        color: #fff;
        -moz-border-radius: 4px;
        -webkit-border-radius: 4px;
        border-radius: 4px;
    }

    .btn-link-1:hover,
    .btn-link-1:focus,
    .btn-link-1:active {
        outline: 0;
        opacity: 0.6;
        color: #fff;
    }

    .btn-link-2 {
        display: inline-block;
        height: 50px;
        margin: 0 5px;
        padding: 15px 20px 0 20px;
        background: rgba(0, 0, 0, 0.3);
        border: 1px solid #fff;
        font-size: 16px;
        font-weight: 300;
        line-height: 16px;
        color: #fff;
        -moz-border-radius: 4px;
        -webkit-border-radius: 4px;
        border-radius: 4px;
    }

    .btn-link-2:hover,
    .btn-link-2:focus,
    .btn-link-2:active,
    .btn-link-2:active:focus {
        outline: 0;
        opacity: 0.6;
        background: rgba(0, 0, 0, 0.3);
        color: #fff;
    }


    /***** Top content *****/

    .form-box {
        padding-top: 2px;
        font-family: 'Roboto', sans-serif !important;
        margin: 0 auto;
    }

    .form-top {
        overflow: hidden;
        height: 83px;
        padding: 0 25px 15px 25px;
        background: #00aeef;
        -moz-border-radius: 4px 4px 0 0;
        -webkit-border-radius: 4px 4px 0 0;
        border-radius: 4px 4px 0 0;
        text-align: left;
        color: #fff;
        transition: opacity .3s ease-in-out;
    }

    .form-top h3 {
        color: #fff;
    }

    .form-bottom {
        padding: 25px 25px 30px 25px;
        background: #fbfbfb;
        -moz-border-radius: 0 0 4px 4px;
        -webkit-border-radius: 0 0 4px 4px;
        border-radius: 0 0 4px 4px;
        text-align: left;
        transition: all .4s ease-in-out;
    }
    /*
    .form-bottom:hover {
        -webkit-box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
        box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
    }
    */

    form .form-bottom button.btn {
        min-width: 105px;
    }

    form .form-bottom .input-error {
        border-color: #d0000f;
        color: #d0000f;
    }

    form.registration-form fieldset {
        display: none;
    }

    ::-webkit-input-placeholder { /* Edge */
        color: #595959;
    }

    :-ms-input-placeholder { /* Internet Explorer */
        color: #595959;
    }

    ::placeholder {
        color: #595959;
    }
    /* The container */
    .containercheck {
        display: block;
        position: relative;
        padding-left: 35px;
        margin-bottom: 12px;
        cursor: pointer;
        font-size: 14px;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        color: #000;
    }

    /* Hide the browser's default checkbox */
    .containercheck input {
        position: absolute;
        opacity: 0;
        cursor: pointer;
        height: 0;
        width: 0;
    }

    /* Create a custom checkbox */
    .checkmark {
        position: absolute;
        top: 0;
        left: 0;
        height: 22px;
        width: 22px;
        background-color: #d2e0e2;
        /* border: 1px solid #999999; */
    }

    /* On mouse-over, add a grey background color */
    .containercheck:hover input ~ .checkmark {
        background-color: #ccc;
    }

    /* When the checkbox is checked, add a blue background */
    .containercheck input:checked ~ .checkmark {
        background-color: #2196F3;
    }

    /* Create the checkmark/indicator (hidden when not checked) */
    .checkmark:after {
        content: "";
        position: absolute;
        display: none;
    }

    /* Show the checkmark when checked */
    .containercheck input:checked ~ .checkmark:after {
        display: block;
    }

    /* Style the checkmark/indicator */
    .containercheck .checkmark:after {
        left: 9px;
        top: 5px;
        width: 5px;
        height: 10px;
        border: solid white;
        border-width: 0 3px 3px 0;
        -webkit-transform: rotate(45deg);
        -ms-transform: rotate(45deg);
        transform: rotate(45deg);
    }
    div.wrap-field ul {
        list-style-type: none;
    }
    .customer-info{
        background: #feffa9ad;
        padding: 10px;
        border-radius: 12px;
        color: #083f65;
        text-align: left;
        margin: 20px;
    }
</style>