<?php
/**
 * @category   Jccbweb
 * @package    Jccbweb_Dbainfo
 * @author     jcc@jccbweb.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Jccbweb\Dbainfo\Controller\Index;

use Magento\Framework\App\Action\Context;
use Jccbweb\Dbainfo\Model\DbainfoFactory;

class Save extends \Magento\Framework\App\Action\Action
{
	/**
     * @var Dbainfo
     */
    protected $_dbainfo;

    public function __construct(
		Context $context,
        DbainfoFactory $dbainfo
    ) {
        $this->_dbainfo = $dbainfo;
        parent::__construct($context);
    }
	public function execute()
    {
        $data = $this->getRequest()->getParams();
    	$dbainfo = $this->_dbainfo->create();
        $dbainfo->setData($data);
        if($dbainfo->save()){
            $this->messageManager->addSuccessMessage(__('You saved the data.'));
        }else{
            $this->messageManager->addErrorMessage(__('Data was not saved.'));
        }
        $resultRedirect = $this->resultRedirectFactory->create();
        $resultRedirect->setPath('mascartdirect/direct/add?id=1');
        return $resultRedirect;
    }
}
