<?php
/**
 * @category   Jccbweb
 * @package    Jccbweb_Dbainfo
 * @author     jcc@jccbweb.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Jccbweb\Dbainfo\Block\Adminhtml\Items\Edit\Tab;

use Magento\Backend\Block\Widget\Form\Generic;
use Magento\Backend\Block\Widget\Tab\TabInterface;

class Main extends Generic implements TabInterface
{
    protected $_wysiwygConfig;
 
    public function __construct(
        \Magento\Backend\Block\Template\Context $context, 
        \Magento\Framework\Registry $registry, 
        \Magento\Framework\Data\FormFactory $formFactory,  
        \Magento\Cms\Model\Wysiwyg\Config $wysiwygConfig, 
        array $data = []
    ) 
    {
        $this->_wysiwygConfig = $wysiwygConfig;
        parent::__construct($context, $registry, $formFactory, $data);
    }

    /**
     * {@inheritdoc}
     */
    public function getTabLabel()
    {
        return __('Item Information');
    }

    /**
     * {@inheritdoc}
     */
    public function getTabTitle()
    {
        return __('Item Information');
    }

    /**
     * {@inheritdoc}
     */
    public function canShowTab()
    {
        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function isHidden()
    {
        return false;
    }

    /**
     * Prepare form before rendering HTML
     *
     * @return $this
     * @SuppressWarnings(PHPMD.NPathComplexity)
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    protected function _prepareForm()
    {
        $model = $this->_coreRegistry->registry('current_jccbweb_dbainfo_items');
        /** @var \Magento\Framework\Data\Form $form */
        $form = $this->_formFactory->create();
        $form->setHtmlIdPrefix('item_');
        $fieldset = $form->addFieldset('base_fieldset', ['legend' => __('Item Information')]);
        if ($model->getId()) {
            $fieldset->addField('dbainfo_id', 'hidden', ['name' => 'dbainfo_id']);
        }

        $fieldset->addField(
            'dbaFirstname',
            'text',
            ['name' => 'dbaFirstname', 'label' => __('First Name'), 'title' => __('First Name'), 'required' => true]
        );


        $fieldset->addField(
            'dbaMiddle',
            'text',
            ['name' => 'dbaMiddle', 'label' => __('Middle'), 'title' => __('Middle'), 'required' => true]
        );

        $fieldset->addField(
            'dbaLastname',
            'text',
            ['name' => 'dbaLastname', 'label' => __('Last Name'), 'title' => __('Last Name'), 'required' => true]
        );

        $fieldset->addField(
            'dbaAddress',
            'text',
            ['name' => 'dbaAddress', 'label' => __('Address'), 'title' => __('Address'), 'required' => true]
        );

        $fieldset->addField(
            'dbaCity',
            'text',
            ['name' => 'dbaCity', 'label' => __('City'), 'title' => __('City'), 'required' => true]
        );
        $fieldset->addField(
            'dbaState',
            'text',
            ['name' => 'dbaState', 'label' => __('State'), 'title' => __('State'), 'required' => true]
        );
        $fieldset->addField(
            'dbaZip',
            'text',
            ['name' => 'dbaZip', 'label' => __('Zip'), 'title' => __('Zip'), 'required' => true]
        );
        $fieldset->addField(
            'dbaPhone',
            'text',
            ['name' => 'dbaPhone', 'label' => __('Phone'), 'title' => __('Phone'), 'required' => true]
        );
        $fieldset->addField(
            'dbaCell',
            'text',
            ['name' => 'dbaCell', 'label' => __('Cell'), 'title' => __('Cell'), 'required' => true]
        );
        $fieldset->addField(
            'dbaEmail',
            'text',
            ['name' => 'dbaEmail', 'label' => __('E-mail'), 'title' => __('E-mail'), 'required' => true]
        );
        $fieldset->addField(
            'dbaOFirstname',
            'text',
            ['name' => 'dbaOFirstname', 'label' => __('O First Name'), 'title' => __('O First Name'), 'required' => true]
        );
        $fieldset->addField(
            'dbaOMiddle',
            'text',
            ['name' => 'dbaOMiddle', 'label' => __('O Middle'), 'title' => __('O Middle'), 'required' => true]
        );
        $fieldset->addField(
            'dbaOLastname',
            'text',
            ['name' => 'dbaOLastname', 'label' => __('O Lastname'), 'title' => __('O Lastname'), 'required' => true]
        );
        $fieldset->addField(
            'dbaOAddress',
            'text',
            ['name' => 'dbaOAddress', 'label' => __('O Address'), 'title' => __('O Address'), 'required' => true]
        );
        $fieldset->addField(
            'dbaOCity',
            'text',
            ['name' => 'dbaOCity', 'label' => __('O City'), 'title' => __('O City'), 'required' => true]
        );
        $fieldset->addField(
            'dbaOState',
            'text',
            ['name' => 'dbaOState', 'label' => __('O State'), 'title' => __('O State'), 'required' => true]
        );

        $fieldset->addField(
            'dbaOZip',
            'text',
            ['name' => 'dbaOZip', 'label' => __('O Zip'), 'title' => __('O Zip'), 'required' => true]
        );
        $fieldset->addField(
            'dbaOPhone',
            'text',
            ['name' => 'dbaOPhone', 'label' => __('O Phone'), 'title' => __('O Phone'), 'required' => true]
        );
        $fieldset->addField(
            'dbaOCell',
            'text',
            ['name' => 'dbaOCell', 'label' => __('O Cell'), 'title' => __('O Cell'), 'required' => true]
        );
        $fieldset->addField(
            'dbaOEmail',
            'text',
            ['name' => 'dbaOEmail', 'label' => __('O Email'), 'title' => __('O Email'), 'required' => true]
        );



        $fieldset->addField(
            'dbaOFirstname2',
            'text',
            ['name' => 'dbaOFirstname2', 'label' => __('O First Name'), 'title' => __('O First Name'), 'required' => true]
        );
        $fieldset->addField(
            'dbaOMiddle2',
            'text',
            ['name' => 'dbaOMiddle2', 'label' => __('O Middle'), 'title' => __('O Middle'), 'required' => true]
        );
        $fieldset->addField(
            'dbaOLastname2',
            'text',
            ['name' => 'dbaOLastname2', 'label' => __('O Lastname'), 'title' => __('O Lastname'), 'required' => true]
        );
        $fieldset->addField(
            'dbaOAddress2',
            'text',
            ['name' => 'dbaOAddress2', 'label' => __('O Address'), 'title' => __('O Address'), 'required' => true]
        );
        $fieldset->addField(
            'dbaOCity2',
            'text',
            ['name' => 'dbaOCity2', 'label' => __('O City'), 'title' => __('O City'), 'required' => true]
        );
        $fieldset->addField(
            'dbaOState2',
            'text',
            ['name' => 'dbaOState2', 'label' => __('O State'), 'title' => __('O State'), 'required' => true]
        );

        $fieldset->addField(
            'dbaOZip2',
            'text',
            ['name' => 'dbaOZip2', 'label' => __('O Zip'), 'title' => __('O Zip'), 'required' => true]
        );
        $fieldset->addField(
            'dbaOPhone2',
            'text',
            ['name' => 'dbaOPhone2', 'label' => __('O Phone'), 'title' => __('O Phone'), 'required' => true]
        );
        $fieldset->addField(
            'dbaOCell2',
            'text',
            ['name' => 'dbaOCell2', 'label' => __('O Cell'), 'title' => __('O Cell'), 'required' => true]
        );
        $fieldset->addField(
            'dbaOEmail2',
            'text',
            ['name' => 'dbaOEmail2', 'label' => __('O Email'), 'title' => __('O Email'), 'required' => true]
        );


        $fieldset->addField(
            'dbaBusiness1',
            'text',
            ['name' => 'dbaBusiness1', 'label' => __('Business 1'), 'title' => __('Business 1'), 'required' => true]
        );

        $fieldset->addField(
            'dbaBusiness2',
            'text',
            ['name' => 'dbaBusiness2', 'label' => __('Business 2'), 'title' => __('Business 2'), 'required' => true]
        );


        $fieldset->addField(
            'dbaBusiness3',
            'text',
            ['name' => 'dbaBusiness3', 'label' => __('Business 3'), 'title' => __('Business 3'), 'required' => true]
        );

        $fieldset->addField(
            'dbaBAddressB',
            'text',
            ['name' => 'dbaBAddressB', 'label' => __('Address B'), 'title' => __('Address B'), 'required' => true]
        );
        $fieldset->addField(
            'startDate',
            'text',
            ['name' => 'startDate', 'label' => __('Start Date'), 'title' => __('Star Date'), 'required' => true]
        );

        $fieldset->addField(
            'status',
            'select',
            ['name' => 'status', 'label' => __('Status'), 'title' => __('Status'),  'options'   => [0 => 'Disable', 1 => 'Enable'], 'required' => true]
        );
        $fieldset->addField(
            'content',
            'editor',
            [
                'name' => 'content',
                'label' => __('Content'),
                'title' => __('Content'),
                'style' => 'height:26em;',
                'required' => true,
                'config'    => $this->_wysiwygConfig->getConfig(),
                'wysiwyg' => true
            ]
        );
        
        $form->setValues($model->getData());
        $this->setForm($form);
        return parent::_prepareForm();
    }
}
