<div class="form-container">


    <form action="<?php echo $block->getBaseUrl().'mform/index/save'; ?>" role="form" id="custom-form" autocomplete="off">
        <input type="hidden"  name="Btype" value="LLC Business"/>

        <input id='step2' type='checkbox'>
        <input id='step3' type='checkbox'>
        <div id="part1" class="form-group">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">LLC - Business Formation Client Questionnaire.</h3>
                    <div class="text-imput">Information about the Organizer/Contact</div>

                </div>
                <!-- Here is the form -->
                <div class="panel-heading">
                    <h3 class="panel-title">INFORMATION ABOUT THE ORGANIZER/CONTACT </h3>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">First Name</div>
                                <input type="text"  name="Firstname"  placeholder="Company First Name" class="required">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">Middle</div>
                                <input type="text"  name="Middle"  placeholder="Company Middle" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">Last Name</div>
                                <input type="text"  name="Lastname"  placeholder="Company Last Name" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                   </div><!--/ end of the row -->


                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">Address</div>
                                <input type="text" name="address"  placeholder="Address" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">City</div>
                                <input type="text"  name="city"  placeholder="City" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                </div><!--// end row -->


                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">State</div>
                                <input type="text" name="state"  placeholder="State" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">Zip</div>
                                <input type="text"  name="zip"  placeholder="Zip" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                </div><!--// end row -->



                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">County of residence or of principal of business :</div>
                                <input type="text" name="contactCounty"  placeholder="County" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">Mailing Address</div>
                                <input type="text"  name="contactMailingaddress"  placeholder="Mailing Address" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                </div><!--// end row -->
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">Telephone Home</div>
                                <input type="text" name="contactPhone"  placeholder="Telephone Home" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">Telephone Business</div>
                                <input type="text"  name="contacPhoneB"  placeholder="Telephone Business" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                </div><!--// end row -->


                <div class="panel-heading">
                        <h3 class="panel-title">INFORMATION ABOUT THE BUSINESS </h3>
                    <div class="text-imput">Check the type of business you would like to open:</div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <div class="wrap-field">
                                <ul style="list-style: none; ">

                                    <li>
                                        <!-- Material unchecked -->
                                        <label class="containercheck">Limited Liability Company(LLC)
                                            <input type="checkbox"  name="option1" value="Limited Liability Company(LLC)">
                                            <span class="checkmark"></span>
                                        </label>
                                    </li>
                                    <li>
                                        <!-- Material unchecked -->
                                        <label class="containercheck">Member Managed
                                            <input type="checkbox"  name="option2" value=">Member Managed">
                                            <span class="checkmark"></span>
                                        </label>
                                    </li>
                                    <li>
                                        <!-- Material unchecked -->
                                        <label class="containercheck">Non Member Managed
                                            <input type="checkbox"  name="option3" value="Non Member Managed">
                                            <span class="checkmark"></span>
                                        </label>
                                    </li>

                                </ul>



                            </div>
                        </div>
                    </div>

                </div><!--// end row -->


                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">Name of the Company 1st Choice</div>
                                <input type="text" name="company1choice"  placeholder="Name of the Company 1st Choice" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">Name of the Company 2nd Choice</div>
                                <input type="text"  name="company2choice"  placeholder="Name of the Company 2nd Choice" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                </div><!--// end row -->

                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">Name of the Company 3rd Choice</div>
                                <input type="text" name="company3choice"  placeholder="NName of the Company 3rd Choice" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">


                            </div>
                        </div>
                    </div>
                </div><!--// end row -->

                <div class="panel-heading">

                    <div class="text-imput">If an LLC, check the ending you would like the business to be:</div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <div class="wrap-field">
                                <ul style="list-style: none; ">


                                    <li>
                                        <!-- Material unchecked -->
                                        <label class="containercheck">LLC
                                            <input type="checkbox"  name="option1ending" value="LLC">
                                            <span class="checkmark"></span>
                                        </label>
                                    </li>
                                    <li>
                                        <!-- Material unchecked -->
                                        <label class="containercheck">L.L.C
                                            <input type="checkbox"   name="option2ending" value="L.L.C">
                                            <span class="checkmark"></span>
                                        </label>
                                    </li>

                                    <li>
                                        <!-- Material unchecked -->
                                        <label class="containercheck">Limited
                                            <input type="checkbox"  name="option3ending" value="Limited">
                                            <span class="checkmark"></span>
                                        </label>
                                    </li>
                                    <li>
                                        <!-- Material unchecked -->
                                        <label class="containercheck">Liability Company
                                            <input type="checkbox"  name="option4ending" value="Liability Company">
                                            <span class="checkmark"></span>
                                        </label>
                                    </li>
                                    <li>
                                        <!-- Material unchecked -->
                                        <label class="containercheck">Ltd.
                                            <input type="checkbox"  name="option5ending" value="Ltd">
                                            <span class="checkmark"></span>
                                        </label>
                                    </li>
                                    <li>
                                        <!-- Material unchecked -->
                                        <label class="containercheck">Liability Co.
                                            <input type="checkbox"  name="option6ending" value="Liability Co.">
                                            <span class="checkmark"></span>
                                        </label>
                                    </li>

                                </ul>

                            </div>
                        </div>
                    </div>

                </div><!--// end row -->


                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">What’s the principal business activity of the business?</div>
                                <input type="text" name="activityBusiness"  placeholder="Activity of the business" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">Address of the Business (NO PO BOX)</div>
                                <input type="text"  name="addressBusiness"  placeholder="Name of the Company 2nd Choice" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                </div><!--// end row -->


                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">City</div>
                                <input type="text"  name="businessCity"  placeholder="BusinessCity" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">State</div>
                                <input type="text" name="businessState"  placeholder="Business State" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">Zip Code</div>
                                <input type="text" name="businessZip"  placeholder="Business Zip Code" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                </div><!--// end row -->


                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">Mailing Address of Business(if different)</div>
                                <input type="text" name="mailingBusiness"  placeholder="Activity of the business" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">

                            </div>
                        </div>
                    </div>
                </div><!--// end row -->


                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">Mailing City</div>
                                <input type="text"  name="mailingbusinessCity"  placeholder="Mailing Business City" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">Mailing State</div>
                                <input type="text" name="mailingbusinessState"  placeholder="Mailing Business State" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">Mailing Zip Code</div>
                                <input type="text" name="mailingbusinessZip"  placeholder="Mailing  Business Zip Code" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                </div><!--// end row -->

                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">Latest date on which the company is to dissolve:</div>
                                <input type="text" name="latestdate"  placeholder="Latest date " class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">(If a corporation, it can   be perpetual)</div>
                                <input type="checkbox"  name="perpetual"  value="yes100" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                </div><!--// end row -->

                 <!--/end of the form -->
                <div class="row">
                    <div class="col-sm-12">
                        <div class="customer-info">
                            INSTRUCTIONS: Answer All questions with an answer or N/A. Today’s date
                            If more space is needed, use the space below or attach blank pages.
                        </div>
                    </div>
                </div>
                <!--/end of the form -->
                <!--/start the second from ************************************************************************************************************  Business Formation Client Questionnaire  ******************************************************-->
                <!--/start the second from ************************************************************************************************************  Business Formation Client Questionnaire  ******************************************************-->
                <!--/start the second from ************************************************************************************************************  Business Formation Client Questionnaire  ******************************************************-->

                <div class="btn-group btn-group-lg" role="group" aria-label="...">
                    <label for='step2' id="continue-step2" class="continue">
                        <div class="btn btn-default btn-success btn-lg action submit primary">Continue</div>
                    </label>
                </div>
            </div>
        </div>
        <div id="part2" class="form-group">
            <div class="panel panel-primary">







                <div class="panel-heading">
                    <h3 class="panel-title">AGENT FOR SERVICE OF PROCESS</h3>
                    <div class="text-imput">Information of the agent for service of process</div>
                </div>


                <!-- Here is the form -->
                <div class="row">

                    <div class="col-sm-4">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">First Name</div>
                                <input type="text"  name="agentFirstname"  placeholder="Company First Name" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">Middle</div>
                                <input type="text"  name="agentMiddle"  placeholder="Company Middle" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">Last Name</div>
                                <input type="text"  name="agentLastname"  placeholder="Company Last Name" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>


                </div><!--/ end of the row -->


                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">Street Address</div>
                                <input type="text" name="agentStreet"  placeholder="Agent Street Address" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">City</div>
                                <input type="text"  name="agentCity"  placeholder="Agent Street City" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                </div><!--// end row -->

                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">State</div>
                                <input type="text" name="agentState"  placeholder="Agent State" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">Zip</div>
                                <input type="text"  name="agentZip"  placeholder="Agent Zip" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                </div><!--// end row -->

                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">Home Phone</div>
                                <input type="text" name="agentPhone"  placeholder="Agent Phone Home" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">Business PHone</div>
                                <input type="text"  name="agentPhoneb"  placeholder="Agent Phone  Business" class="form-control valid only_character js-upper-first required">
                            </div>
                        </div>
                    </div>
                </div><!--// end row -->




                <!--// ***************************************************************************************************************************************************** -->
                <!--// ***************************************************************************************************************************************************** -->






                <!--/end of the form -->
                <div class="btn-group btn-group-lg btn-group-justified" role="group" aria-label="...">
                    <label for='step2' id="back-step2" class="back">
                        <div class="btn btn-default btn-primary btn-lg" role="button">Back</div>
                    </label>
                    <label for='step3' id="continue-step3" class="continue">
                        <div class="btn btn-default btn-success btn-lg" role="button">Continue</div>
                    </label>
                </div>
            </div> <!--/ end of the panel -->
        </div>
        <div id="part3" class="form-group">
            <div class="panel panel-primary">

                <div class="panel-heading">
                        <h3 class="panel-title">For an LLC, the company will be managed by:</h3>

                </div>


                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <div class="wrap-field">
                                <ul style="list-style: none; ">


                                    <li>
                                        <!-- Material unchecked -->
                                        <label class="containercheck">One Manager
                                            <input type="checkbox"  name="moption1" value="One Manager">
                                            <span class="checkmark"></span>
                                        </label>
                                    </li>
                                    <li>
                                        <!-- Material unchecked -->
                                        <label class="containercheck">More then one manager
                                            <input type="checkbox"   name="moption2" value="More then one manager">
                                            <span class="checkmark"></span>
                                        </label>
                                    </li>

                                    <li>
                                        <!-- Material unchecked -->
                                        <label class="containercheck">limited liability
                                            <input type="checkbox"  name="moption3" value="limited liability">
                                            <span class="checkmark"></span>
                                        </label>
                                    </li>
                                    <li>
                                        <!-- Material unchecked -->
                                        <label class="containercheck">company members
                                            <input type="checkbox"   name="moption4" value="company members">
                                            <span class="checkmark"></span>
                                        </label>
                                    </li>


                                </ul>

                            </div>
                        </div>
                    </div>

                </div><!--// end row -->



                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <div class="wrap-field">
                                <div class="text-imput">For an LLC, state any additional provisions that limit the business or authority of managers
                                    or members:</div>
                                <textarea name="content" class="form-control" placeholder="Message"></textarea>
                            </div>
                        </div>
                    </div>
                </div> <!--/ end of the row -->












                <div class="btn-group btn-group-lg" role="group" aria-label="...">
                    <label for='step3' id="back-step3" class="back">
                        <div class="btn btn-default btn-primary btn-lg">Back</div>
                    </label>



                    <label class="continue">
                        <button type="submit" class="btn btn-default buttonprimary">Submit</button>
                    </label>
                </div>
            </div>


        </div><!-- // end of the part3  -->
    </form>
</div> <!-- // end of the container -->



<!-- jQuery -->
<!-- /.MultiStep Form -->
<style>
    /*form styles*/
    .form-container {
        width: 100%;
        max-width: 1020px;
        margin: 0 auto;
    }
    .form-container input[type=text], .form-container input[type=email], .form-container input[type=phone], .form-container input[type=number], .form-container textarea {
        width: 95%;
        margin: 10px 10px;
        border: 1px solid #fffdfd;
        box-shadow: 0 0 1px 1px #d6cfcf;
        text-align: left;
    }
    .panel-title{
        color: #31aeef;
        font-weight: 600;
        text-align: left;
        margin-left: 25px;
        margin-top: 25px;
    }
    .text-imput{
        text-align: left;
        margin-left: 28px;
        font-weight: 500;
        color: #000;
    }
    .form-container textarea {
        min-height: 150px;
    }
    .form-container .panel {
        background: #f9f9f9;
        padding: 10px;
        border-radius: 12px;
        padding-bottom: 75px;
    }
    .buttonprimary {
        border: 1px solid #ea3c00 !important;
        color: #fff !important;
        font-weight: 700;
        line-height: 30px !important;
        padding: 0 12px !important;
        height: 45px !important;
        background-color: #ff5216 !important;
    }
    .customer-info{
        background: #feffa9ad;
        padding: 10px;
        border-radius: 12px;
        color: #083f65;
        text-align: left;
        margin: 20px;
    }
    .form-container .panel .panel-heading {
        margin-bottom: 20px;
    }
    .form-container .btn-group {
        width: 90%;
        margin: 0 auto 10px auto;
        padding-top: 25px;
    }
    .form-container .back {
        float: left;
    }
    .form-container .continue {
        float: right;
    }
    /* Multi-Part CSS */
    input[type=checkbox] {
        position: absolute;
        /* Position the checkbox in upper left corner */
        opacity: 0;
    }
    /* Styling Parts */
    #part1,
    #part2,
    #part3 {
        z-index: 2;
        display: block;
        height: auto;
        opacity: 1;
        transition: opacity 1s ease-in-out;
    }
    /* Hidden Parts */
    #part2,
    #part3 {
        opacity: 0;
        height: 0;
        overflow: hidden;
    }
    /* Show Step 2 & Hide Step 1 */
    #step2:checked ~ #part2 {
        opacity: 1;
        height: auto;
    }
    #step2:checked ~ #part1 {
        opacity: 0;
        height: 0;
        display: none;
    }
    /* Show Step 3  & Hide Step 2 */
    #step3:checked ~ #part3 {
        opacity: 1;
        height: auto;
    }
    #step3:checked ~ #part2 {
        opacity: 0;
        width: 0;
        height: 0;
    }
    /* The container */
    .containercheck {
        display: block;
        position: relative;
        padding-left: 35px;
        margin-bottom: 12px;
        cursor: pointer;
        font-size: 14px;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        color: #000;
    }

    /* Hide the browser's default checkbox */
    .containercheck input {
        position: absolute;
        opacity: 0;
        cursor: pointer;
        height: 0;
        width: 0;
    }

    /* Create a custom checkbox */
    .checkmark {
        position: absolute;
        top: 0;
        left: 0;
        height: 22px;
        width: 22px;
        background-color: #d2e0e2;
        /* border: 1px solid #999999; */
    }

    /* On mouse-over, add a grey background color */
    .containercheck:hover input ~ .checkmark {
        background-color: #ccc;
    }

    /* When the checkbox is checked, add a blue background */
    .containercheck input:checked ~ .checkmark {
        background-color: #2196F3;
    }

    /* Create the checkmark/indicator (hidden when not checked) */
    .checkmark:after {
        content: "";
        position: absolute;
        display: none;
    }

    /* Show the checkmark when checked */
    .containercheck input:checked ~ .checkmark:after {
        display: block;
    }

    /* Style the checkmark/indicator */
    .containercheck .checkmark:after {
        left: 9px;
        top: 5px;
        width: 5px;
        height: 10px;
        border: solid white;
        border-width: 0 3px 3px 0;
        -webkit-transform: rotate(45deg);
        -ms-transform: rotate(45deg);
        transform: rotate(45deg);
    }
    div.wrap-field ul {
        list-style-type: none;
    }


</style>

<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.16.0/jquery.validate.min.js"></script>
<script>

    require([
        "jquery"
    ], function($){
        $(document).ready(function() {
            alert("version 10");
            $("#part1").validate({
                rules: {
                    firstname: "required",
                    lastname: "required",
                    username: {
                        required: true,
                        minlength: 2
                    },
                    password: {
                        required: true,
                        minlength: 5
                    },
                    confirm_password: {
                        required: true,
                        minlength: 5,
                        equalTo: "#password"
                    },
                    email: {
                        required: true,
                        email: true
                    },
                    topic: {
                        required: "#newsletter:checked",
                        minlength: 2
                    },
                    agree: "required"
                },
                messages: {
                    firstname: "Please enter your firstname",
                    lastname: "Please enter your lastname",
                    username: {
                        required: "Please enter a username",
                        minlength: "Your username must consist of at least 2 characters"
                    },
                    password: {
                        required: "Please provide a password",
                        minlength: "Your password must be at least 5 characters long"
                    },
                    confirm_password: {
                        required: "Please provide a password",
                        minlength: "Your password must be at least 5 characters long",
                        equalTo: "Please enter the same password as above"
                    },
                    email: "Please enter a valid email address",
                    agree: "Please accept our policy",
                    topic: "Please select at least 2 topics"
                }
            });







        });
    });

</script>
<!--
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js" type="text/javascript"></script>
<link rel='stylesheet' id='theme-font-css'  href='https://cdnjs.cloudflare.com/ajax/libs/foundation/5.3.1/css/foundation.min.css' media='all' />
<script type='text/javascript' src='https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js'></script>
<script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js'></script>
-->
